# Generated by Django 4.2.10 on 2024-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='linkLang',
            field=models.CharField(default='', max_length=200),
        ),
    ]
