# Generated by Django 4.2.10 on 2024-02-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_ghost_project_linkvideo_alter_project_linkhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
